server:
  port: 8081

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
# H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true     # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      settings:         # H2 Console의 Path
        web-allow-others: true
        path: /h2-console

jpa:
  hibernate:
    ddl-auto: none;
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

# Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:testdb     # H2 접속 정보